/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectohotel;

import javax.swing.JOptionPane;
/**
 *
 * @author Lucas
 */
public class VentanaReservas extends javax.swing.JFrame {

    /**
     * private Creates new form VentanaReservas
     */
    private Hotel hotel; //declaramos el atributo HOTEL 

    public VentanaReservas() { //inicializamos la clase ventana - 
        initComponents();
        hotel = new Hotel();
        txtNroHabitacion.requestFocus();//hace el foco en el txt habitacion
        rbtVigente.setSelected(true);//NO SE PARA QUE SIRVE LO DE VIGENTE, ESTABA EN EL ENUNCIADO, SIEMPRE LO DEJAMOS EN TRUE
        txtCantidadNiños.setEnabled(false);//DESHABILITA EL TXT HASTA QUE SELECCIONEMOS SI VAMOS DE VACACIONES
        txtAreaCantidadReservasTipo.setEnabled(false); //DESHABILITA EL TEXT AREA DONDE VA A MOSTRAR EL REPORTE(LO HABILITAMOS CUANDO HACEMOS EL REPORTE)
        chckBoxCnferencia.setEnabled(false); // DESHABILITA EL CHECKBOX CONFERENCIA
        

    }

    public void limpiarCampos() {
        txtAreaCantidadReservasTipo.setText("");//EL TXT DIRECCION???
        txtNroHabitacion.setText("");//limpiamos txt habitacion
        txtDiasReservados.setText(""); //limpiamos txt dias reservados
        txtCantidadNiños.setText("");//limpiamos txt cantidad niños
        txtTarifa.setText("");//limpiamos txt tarifas


        chckBoxCnferencia.setSelected(false);// DESHABILITA EL CHECKBOX CONFERENCIA
        txtCantidadNiños.setEnabled(false);// DESHABILITA EL TEXT BOX CANTIDAD NIÑOS
        
        lblFacturacionTotalMetodo.setText("");
        buttonTipoReserva.clearSelection();//LIMPIA TODO LOS BOTONES
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonTipoReserva = new javax.swing.ButtonGroup();
        txtNroHabitacion = new javax.swing.JTextField();
        lblNroHabitacion = new javax.swing.JLabel();
        txtDiasReservados = new javax.swing.JTextField();
        lblDiasReservados = new javax.swing.JLabel();
        rbtVigente = new javax.swing.JRadioButton();
        rbtVacaciones = new javax.swing.JRadioButton();
        rbtNegocios = new javax.swing.JRadioButton();
        lblCantidadDeNiños = new javax.swing.JLabel();
        txtCantidadNiños = new javax.swing.JTextField();
        chckBoxCnferencia = new javax.swing.JCheckBox();
        btnReservar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTarifa = new javax.swing.JTextField();
        lblReportes = new javax.swing.JLabel();
        lblFacturacionTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCantidadReservasTipo = new javax.swing.JTextArea();
        lblFacturacionTotalMetodo = new javax.swing.JLabel();
        btnMostrarReporte = new javax.swing.JButton();
        btnNuevaReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNroHabitacion.setText("Nro Habitacion");

        txtDiasReservados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiasReservadosActionPerformed(evt);
            }
        });

        lblDiasReservados.setText("Días Reservados");

        rbtVigente.setText("Vigente");
        rbtVigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtVigenteActionPerformed(evt);
            }
        });

        buttonTipoReserva.add(rbtVacaciones);
        rbtVacaciones.setText("Vacaciones");
        rbtVacaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtVacacionesActionPerformed(evt);
            }
        });

        buttonTipoReserva.add(rbtNegocios);
        rbtNegocios.setText("Negocios");
        rbtNegocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNegociosActionPerformed(evt);
            }
        });

        lblCantidadDeNiños.setText("Cantidad de Niños");

        txtCantidadNiños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadNiñosActionPerformed(evt);
            }
        });

        chckBoxCnferencia.setText("Es Conferencia");
        chckBoxCnferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckBoxCnferenciaActionPerformed(evt);
            }
        });

        btnReservar.setText("RESERVAR");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        jLabel1.setText("Tarifa:");

        lblReportes.setText("REPORTES");

        lblFacturacionTotal.setText("Facturacion Total Prevista:");

        txtAreaCantidadReservasTipo.setColumns(20);
        txtAreaCantidadReservasTipo.setRows(5);
        jScrollPane1.setViewportView(txtAreaCantidadReservasTipo);

        lblFacturacionTotalMetodo.setText("-");

        btnMostrarReporte.setText("Mostrar Reportes");
        btnMostrarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarReporteActionPerformed(evt);
            }
        });

        btnNuevaReserva.setText("NUEVA RESERVA");
        btnNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnReservar)
                                    .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(rbtNegocios, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtVacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCantidadDeNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCantidadNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDiasReservados)
                                        .addGap(66, 66, 66)
                                        .addComponent(txtDiasReservados, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNroHabitacion)
                                        .addGap(66, 66, 66)
                                        .addComponent(txtNroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(chckBoxCnferencia)
                                    .addGap(94, 94, 94)))
                            .addComponent(rbtVigente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblFacturacionTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFacturacionTotalMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblReportes)
                                .addGap(119, 119, 119))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnMostrarReporte)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(btnNuevaReserva)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNroHabitacion)
                            .addComponent(lblReportes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiasReservados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiasReservados))
                        .addGap(18, 18, 18)
                        .addComponent(rbtVigente)
                        .addGap(10, 10, 10)
                        .addComponent(rbtVacaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidadDeNiños)
                            .addComponent(txtCantidadNiños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtNegocios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chckBoxCnferencia)
                            .addComponent(btnMostrarReporte))
                        .addGap(11, 11, 11)
                        .addComponent(btnReservar)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFacturacionTotal)
                            .addComponent(lblFacturacionTotalMetodo))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addComponent(btnNuevaReserva)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtVigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtVigenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtVigenteActionPerformed

    private void txtDiasReservadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiasReservadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasReservadosActionPerformed

    private void rbtVacacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtVacacionesActionPerformed
        // TODO add your handling code here:
        txtCantidadNiños.setEnabled(true);//habilita el txt para que lo podamos llenar
        txtCantidadNiños.requestFocus(); // hace foco en la caja
        chckBoxCnferencia.setEnabled(false);//deshabilita el checkbox
    }//GEN-LAST:event_rbtVacacionesActionPerformed

    private void txtCantidadNiñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadNiñosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadNiñosActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
        
        int nroHabitacion= Integer.parseInt(txtNroHabitacion.getText());//convertimos el valor de nrohabitacion en int para crear la reserva
        int cantDias= Integer.parseInt(txtDiasReservados.getText());//convertimos el valor de nrohabitacion en int int para hacer la reserva
        boolean vigente= rbtVigente.isSelected();//toma el true de vigente para crear la reserva reserva
        if (rbtVacaciones.isSelected()) {
                        
            int cantNinios=Integer.parseInt(txtCantidadNiños.getText());//CONVIERTE EN INT LO QUE ESTA EN EL TEXT BOX DE CANTIDAD DE NIÑOS
            Vacaciones nuevavacaciones= new Vacaciones(cantNinios, nroHabitacion, cantDias, vigente);//CREAMOS OBJETO VACACIONS
            hotel.agregarReserva(nuevavacaciones);//AGREGAMOS LA VACACION A LA LISTA DE RESERVAS DEL HOTEL   
            txtTarifa.setText(String.valueOf(nuevavacaciones.calcularTarifa()));//CONVIERTE EN STRING EL METODO CALCULAR TARIFA DE NUEVAVACACIONES
        }
        else  {
            boolean conferencia= chckBoxCnferencia.isSelected();
            Negocios nuevoNegocios = new Negocios(conferencia, nroHabitacion, cantDias, vigente);
            hotel.agregarReserva(nuevoNegocios); //AGREGAMOS EL NEGOCIO A LA LISTA DE RESERVAS DEL HOTEL
            txtTarifa.setText(String.valueOf(nuevoNegocios.calcularTarifa()));//CONVIERTE EN STRING EL METODO CALCULAR TARIFA DE NUEVAVACACIONES
        }
       
        
//        txtTarifa.setText(String.valueOf(hotel.getReservas());
//        pruebita.set
        //pruebita.(hotel.getReservas().toArray());//PARA MOSTRAR LOS OBJETOS EN EL LIST DEL FORM

        JOptionPane.showMessageDialog(this, "Reserva registrada con exito");
        
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaReservaActionPerformed
        // TODO add your handling code here:
        
        limpiarCampos();//EJECUTA EL METODO LIMPIAR CAMPOS
    }//GEN-LAST:event_btnNuevaReservaActionPerformed

    private void btnMostrarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarReporteActionPerformed
    lblFacturacionTotalMetodo.setText("$" + String.valueOf(hotel.facturacionTotal()));// TODO add your handling code here:
    txtAreaCantidadReservasTipo.setText(hotel.cantReservaPorTipo());
    txtAreaCantidadReservasTipo.setEditable(false);//NO TE DEJA EDITAR EL TEXT AREA
    txtAreaCantidadReservasTipo.setEnabled(true);//HABILITA EL TEXT AREA, SOLO LO PUSE PARA QUE SE PONGA BLANQUITO
     
    }//GEN-LAST:event_btnMostrarReporteActionPerformed

    private void rbtNegociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNegociosActionPerformed
        // TODO add your handling code here:
        txtCantidadNiños.setEnabled(false);//deshabilita la caja de texto
         txtCantidadNiños.setText("");//limpia la caja de texto
        chckBoxCnferencia.setEnabled(true); //habilita el checkbox
        
    }//GEN-LAST:event_rbtNegociosActionPerformed

    private void chckBoxCnferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckBoxCnferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chckBoxCnferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarReporte;
    private javax.swing.JButton btnNuevaReserva;
    private javax.swing.JButton btnReservar;
    private javax.swing.ButtonGroup buttonTipoReserva;
    private javax.swing.JCheckBox chckBoxCnferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidadDeNiños;
    private javax.swing.JLabel lblDiasReservados;
    private javax.swing.JLabel lblFacturacionTotal;
    private javax.swing.JLabel lblFacturacionTotalMetodo;
    private javax.swing.JLabel lblNroHabitacion;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JRadioButton rbtNegocios;
    private javax.swing.JRadioButton rbtVacaciones;
    private javax.swing.JRadioButton rbtVigente;
    private javax.swing.JTextArea txtAreaCantidadReservasTipo;
    private javax.swing.JTextField txtCantidadNiños;
    private javax.swing.JTextField txtDiasReservados;
    private javax.swing.JTextField txtNroHabitacion;
    private javax.swing.JTextField txtTarifa;
    // End of variables declaration//GEN-END:variables
}
