/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoBanco;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class ventanaBanco extends javax.swing.JFrame {

    private Banco banco;
    private JComboBox combo;

    public ventanaBanco() {
        initComponents();
        banco = new Banco();
        cargarCombo(cboTipoTarjetaAgregar);
        cargarCombo(cboTipoTarjetaConsultar);
        cboTipoTarjetaAgregar.setSelectedIndex(-1);
        cboTipoTarjetaConsultar.setSelectedIndex(-1);

    }

    public void cargarCombo(JComboBox combo) {
        combo.removeAllItems();
        combo.addItem("Tarjeta de Debito");
        combo.addItem("Tarjeta de Credito");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoTarjetas = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cboTipoTarjetaConsultar = new javax.swing.JComboBox<>();
        txtNumeroTarjeta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLimite = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        btnMostrarReportes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        lblSaldoTD = new javax.swing.JLabel();
        lblPromedioTC = new javax.swing.JLabel();
        rbtExtraccion = new javax.swing.JRadioButton();
        rbtDeposito = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        txtTarjetaOperar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtImporteOperar = new javax.swing.JTextField();
        btnOperar = new javax.swing.JButton();
        TipoTarjeta = new javax.swing.JLabel();
        cboTipoTarjetaAgregar = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Numero");

        cboTipoTarjetaConsultar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("TipoTarjeta:");

        jLabel3.setText("Saldo:");

        jLabel4.setText("Limite");

        jLabel5.setText("Titular:");

        btnMostrarReportes.setText("Mostrar Reportes");
        btnMostrarReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarReportesActionPerformed(evt);
            }
        });

        jLabel6.setText("El saldo total de tarjetas de debito es de:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblSaldoTD.setText("0");

        lblPromedioTC.setText("0");

        TipoTarjetas.add(rbtExtraccion);
        rbtExtraccion.setText("Extraccion");

        TipoTarjetas.add(rbtDeposito);
        rbtDeposito.setText("Deposito");

        jLabel10.setText("Numero Tarjeta:");

        jLabel11.setText("Importe:");

        btnOperar.setText("Operar");
        btnOperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperarActionPerformed(evt);
            }
        });

        TipoTarjeta.setText("TipoTarjeta:");

        cboTipoTarjetaAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTipoTarjetaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoTarjetaAgregarActionPerformed(evt);
            }
        });

        jLabel12.setText("El promedio de saldo de tarjetas de credito es de:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(TipoTarjeta))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboTipoTarjetaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarReportes)
                    .addComponent(txtTarjetaOperar)
                    .addComponent(txtImporteOperar))
                .addGap(151, 151, 151))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaldoTD)
                    .addComponent(lblPromedioTC))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(cboTipoTarjetaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(rbtExtraccion)
                        .addGap(37, 37, 37)
                        .addComponent(rbtDeposito))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(btnOperar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(btnAgregar)
                    .addContainerGap(503, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblSaldoTD)
                    .addComponent(TipoTarjeta)
                    .addComponent(cboTipoTarjetaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblPromedioTC)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnMostrarReportes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(rbtExtraccion)
                    .addComponent(rbtDeposito))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTipoTarjetaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTarjetaOperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImporteOperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(32, 32, 32)
                .addComponent(btnOperar)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(200, Short.MAX_VALUE)
                    .addComponent(btnAgregar)
                    .addGap(205, 205, 205)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboTipoTarjetaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoTarjetaAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoTarjetaAgregarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int numero = Integer.parseInt(txtNumeroTarjeta.getText());
        float saldo = Float.parseFloat(txtSaldo.getText());
        String titular = txtTitular.getText();

        if (cboTipoTarjetaAgregar.getSelectedIndex() == 0) {
            Debito td = new Debito(numero, saldo, titular);
            banco.agregarTarjeta(td);

        } else if (cboTipoTarjetaAgregar.getSelectedIndex() == 1) {
            float limite = Float.parseFloat(txtLimite.getText());
            Credito tc = new Credito(limite, numero, saldo, titular);
            banco.agregarTarjeta(tc);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnMostrarReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarReportesActionPerformed
        float saldoTD = banco.saldoTotalTD();
        float promedioTC = banco.saldoPromedioTC();
        lblSaldoTD.setText("" + saldoTD);
        lblPromedioTC.setText("" + promedioTC);

    }//GEN-LAST:event_btnMostrarReportesActionPerformed

    private void btnOperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperarActionPerformed
        int numero = Integer.parseInt(txtTarjetaOperar.getText());
        float importe = Float.parseFloat(txtImporteOperar.getText());
        int tipo = cboTipoTarjetaAgregar.getSelectedIndex();
        boolean exito = false;
        
        if (rbtExtraccion.isSelected()) {
            exito = banco.extraer(numero, tipo, importe);            
        }else if(rbtDeposito.isSelected()){
            exito = banco.depositar(numero, tipo, importe);
        }
        if (exito) {
            JOptionPane.showMessageDialog(null,"OK");
            
        }
        else
        {JOptionPane.showMessageDialog(null,"Fallo la operacion");}

    }//GEN-LAST:event_btnOperarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TipoTarjeta;
    private javax.swing.ButtonGroup TipoTarjetas;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnMostrarReportes;
    private javax.swing.JButton btnOperar;
    private javax.swing.JComboBox<String> cboTipoTarjetaAgregar;
    private javax.swing.JComboBox<String> cboTipoTarjetaConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblPromedioTC;
    private javax.swing.JLabel lblSaldoTD;
    private javax.swing.JRadioButton rbtDeposito;
    private javax.swing.JRadioButton rbtExtraccion;
    private javax.swing.JTextField txtImporteOperar;
    private javax.swing.JTextField txtLimite;
    private javax.swing.JTextField txtNumeroTarjeta;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTarjetaOperar;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables
}
